// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableDisks() {
  return window['go']['main']['App']['GetAvailableDisks']();
}

export function GetCopyProgress() {
  return window['go']['main']['App']['GetCopyProgress']();
}

export function GetDiskInfo(arg1) {
  return window['go']['main']['App']['GetDiskInfo'](arg1);
}

export function StartForensicCopy(arg1, arg2) {
  return window['go']['main']['App']['StartForensicCopy'](arg1, arg2);
}

export function StopCopy() {
  return window['go']['main']['App']['StopCopy']();
}

export function ValidateSourceDisk(arg1) {
  return window['go']['main']['App']['ValidateSourceDisk'](arg1);
}

export function ValidateTargetDisk(arg1) {
  return window['go']['main']['App']['ValidateTargetDisk'](arg1);
}
