// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function FormatTargetDisks(arg1:Array<string>,arg2:string):Promise<void>;

export function GetAvailableDisks():Promise<Array<models.DiskInfo>>;

export function GetDiskInfo(arg1:string):Promise<models.DiskInfo>;

export function StartForensicCopy(arg1:string,arg2:Array<string>):Promise<void>;

export function StartRawCopy(arg1:string,arg2:Array<string>):Promise<void>;

export function StopCopy():Promise<void>;

export function ValidateSourceDisk(arg1:string):Promise<void>;

export function ValidateTargetDisk(arg1:string):Promise<void>;
